export const IMAGES = {
  icon_black_white: require("../../assets/chat-icon-png-black-white.png"),
  icon_png: require("../../assets/chat-icon-png.png"),
  icon: require("../../assets/chat-icon.png"),
  back_chat: require("../../assets/back-chat.png"),
  send: require("../../assets/send.png"),
  photo: require("../../assets/photo.png"),
  dots: require("../../assets/more.png"),
  back: require("../../assets/arrow.png"),
  filter: require("../../assets/filter.png"),
  invite: require("../../assets/invitation.png"),
  check: require("../../assets/check.png"),
  close: require("../../assets/close.png"),
  plus: require("../../assets/plus.png"),
  copy: require("../../assets/copy.png"),
  women: require("../../assets/women.png"),
  men: require("../../assets/men.png"),
  profile: require("../../assets/user.png"),
  chat: require("../../assets/chat.png"),
  search: require("../../assets/search.png"),
  paste: require("../../assets/paste.png"),
  no_photo: require("../../assets/no-image.png"),
  pass_unvisible: require("../../assets/hide.png"),
  pass_visible: require("../../assets/visible.png"),
  star: require("../../assets/star.png"),
};
